version: '3.7'

services:
  mysql_thefthing:  
    image: mysql:5.7
    container_name: mysql_thefthing
    hostname: mysql_thefthing
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=thefthing
    restart: unless-stopped
    ports:
      - 33066:3306
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_root_password

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    hostname: backend
    restart: unless-stopped
    ports:
      - "5000:80"
    depends_on:
      - mysql_thefthing

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    hostname: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  mysql-data:

networks:
  default:
